---
author: 'Lucas van der Meer'
date: 'February 25, 2019'
institution: 'University of Münster'
division: 'Institue for Geoinformatics'
advisor: 'Prof. Dr. Edzer Pebesma'
degree: 'Master of Science'
title: 'Spatio-Temporal Forecasts for Bike Availability in Dockless Bike Sharing Systems'
knit: "bookdown::render_book"
site: bookdown::bookdown_site
output:
 #thesisdown::thesis_pdf: default
 thesisdown::thesis_gitbook: default
abstract: |
  `r if(knitr:::is_latex_output()) paste(readLines("abstract.Rmd"), collapse = '\n  ')`
acknowledgements: |
  This thesis, and in the broader sense, my whole period as a student, would not have been possible without the help and support of others. It still feels somewhat strange, that by writing these words, a seven-year journey comes to an end. I want to thank my family, and in particular my parents, for their unconditional support, also in times when I made wrong decisions. Lore, thank you for cheering me up whenever I needed it, and my friends and classmates, thank you for being like a family! \par

  I want to thank all my teachers for sharing their knowledge, despite making me suffer with homework and assignments! In particular, I want to thank my supervisor, Edzer Pebesma, for providing guidance whenever necessary, but also constantly encouraging an independent way of working and thinking, in which own thoughts and ideas are important. Additionally, I want to thank my co-supervisors, Jorge Mateu and Joel Silva, for their valuable feedback. Thanks also to the whole r-spatial community, for providing open source tools, and encouraging involvement and contributions, within an environment that makes everyone feel equally valued. \par

  Finally, I owe gratitude to JUMP Bikes, and Alexander Tedeschi in particular, for providing me with very useful data.
  <!-- \clearpage -->
  <!-- \shipout\null -->
  <!-- \stepcounter{page} -->
dedication: |
  \begin{tabbing}
  ACF \hspace{3em} \=  Autocorrelation Function \\
  AIC \>  Aikake’s Information Criterion \\
  AR \> Autoregressive \\
  ARIMA \> Autoregressive Integrated Moving Average \\
  ARMA \> Autoregressive Moving Average \\
  DBAFS \> Dockless Bike Availability Forecasting System \\
  GPS \>  Global Positioning System \\
  ID \> Identification \\
  KPSS \>  Kwiatkowski-Phillips-Schmidt-Shin \\
  MA \> Moving Average \\
  MAE \> Mean Absolute Error \\
  MLE \> Maximum Likelihood Estimation \\
  NFS \> Naïve Forecasting System \\
  PACF \> Partial Autocorrelation Function \\
  PDT \>  Pacific Daylight Saving Time \\
  PST \> Pacific Standard Time \\
  PBSS \> Public Bike Sharing Systems \\
  RMSE \> Root Mean Squared Error \\
  RMSLE \> Root Mean Squared Logarithmic Error \\
  SFMTA \>  San Francisco Municipal Transportation Agency \\
  SQL \>  Structured Query Language \\
  STL \>  Seasonal Trend decomposition procedure based on Loess \\
  WGS84 \> World Geodetic System 1984
  \end{tabbing}
  <!-- \clearpage -->
  <!-- \shipout\null -->
  <!-- \stepcounter{page} -->
bibliography: bib/references.bib
csl: csl/apa.csl
link-citations: true
toc: true
toc-depth: 4
lot: true
lof: true
space_between_paragraphs: true
header-includes:
  - \usepackage{caption}
  - \usepackage{array}
  - \usepackage{booktabs}
  - \usepackage{makecell}
  - \usepackage{longtable}
  - \usepackage{multirow}
  - \usepackage{wrapfig}
  - \usepackage{float}
  - \usepackage{colortbl}
  - \usepackage{pdflscape}
  - \usepackage{tabu}
  - \usepackage{threeparttable}
  - \usepackage{threeparttablex}
  - \usepackage[normalem]{ulem}
  - \usepackage{xcolor}
  - \usepackage{wrapfig}
  - \usepackage{graphicx}
  - \usepackage{parskip}
  - \usepackage[font=footnotesize,labelfont=bf, width=\textwidth]{caption}
  - \usepackage[hidelinks]{hyperref}
  - \usepackage[T1]{fontenc}
---

<!--
Above is the YAML (YAML Ain't Markup Language) header that includes a lot of metadata used to produce the document.  Be careful with spacing in this header!

If you'd prefer to not include a Dedication, for example, simply delete lines 17 and 18 above or add a # before them to comment them out.  If you have other LaTeX packages you would like to include, delete the # before header-includes and list the packages after hyphens on new lines.

If you'd like to include a comment that won't be produced in your resulting file enclose it in a block like this.
-->

<!--
If you receive a duplicate label error after knitting, make sure to delete the index.Rmd file and then knit again.
-->

```{r include_packages, include = FALSE}
# This chunk ensures that the thesisdown package is
# installed and loaded. This thesisdown package includes
# the template files for the thesis.
if(!require(devtools))
  install.packages("devtools", repos = "http://cran.rstudio.com")
if(!require(thesisdown))
  devtools::install_github("ismayc/thesisdown")
library(knitr)
library(kableExtra)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(out.width = "\\textwidth")
```

<!-- You'll need to include the order that you'd like Rmd files to appear in the _bookdown.yml file for
PDF files and also delete the # before rmd_files: there.  You'll want to not include 00(two-hyphens)prelim.Rmd
and 00-abstract.Rmd since they are handled in the YAML above differently for the PDF version.
-->

<!-- The {.unnumbered} option here means that the introduction will be "Chapter 0." You can also use {-} for no numbers
on chapters.
-->